#!/bin/bash

PROJECT_ROOT="luna-os"

DIRS=(
    "$PROJECT_ROOT/include"
    "$PROJECT_ROOT/arch/x86"
    "$PROJECT_ROOT/arch/arm64"
    "$PROJECT_ROOT/arch/riscv"
    "$PROJECT_ROOT/kernel/ai/explicit"
    "$PROJECT_ROOT/kernel/ai/neural"
    "$PROJECT_ROOT/user/lexer"
    "$PROJECT_ROOT/user/shell"
    "$PROJECT_ROOT/ipc"
    "$PROJECT_ROOT/compositor"
    "$PROJECT_ROOT/drivers/gfx"
    "$PROJECT_ROOT/drivers/input"
    "$PROJECT_ROOT/drivers/serial"
    "$PROJECT_ROOT/tools/nettools"
    "$PROJECT_ROOT/tools/pentest"
    "$PROJECT_ROOT/tools/forensics"
    "$PROJECT_ROOT/tools/crypto"
    "$PROJECT_ROOT/tools/filehasher"
    "$PROJECT_ROOT/apps/textedit"
    "$PROJECT_ROOT/apps/wordedit"
    "$PROJECT_ROOT/apps/spreadsheet"
    "$PROJECT_ROOT/apps/calculator"
)

echo "[*] Initializing Luna OS Directory Tree..."
for dir in "${DIRS[@]}"; do
    if [ ! -d "$dir" ]; then
        mkdir -p "$dir"
        echo "  [+] Created: $dir"
    fi
done
echo "[*] Directory tree structure enforced."
echo ""

FILES=(
    "$PROJECT_ROOT/kernel/ai/explicit/explicit.h"
    "$PROJECT_ROOT/kernel/ai/explicit/rule_table.c"
    "$PROJECT_ROOT/kernel/ai/ai_core.c"
    "$PROJECT_ROOT/kernel/ai/ai_core.h"
    "$PROJECT_ROOT/Makefile"
    "$PROJECT_ROOT/linker.ld"
    "$PROJECT_ROOT/include/types.h"
    "$PROJECT_ROOT/include/math_prim.h"
    "$PROJECT_ROOT/include/panic.h"
    "$PROJECT_ROOT/arch/x86/boot.asm"
    "$PROJECT_ROOT/arch/x86/gdt.c"
    "$PROJECT_ROOT/arch/x86/gdt.h"
    "$PROJECT_ROOT/arch/x86/gdt_flush.asm"
    "$PROJECT_ROOT/arch/x86/idt.c"
    "$PROJECT_ROOT/arch/x86/idt.h"
    "$PROJECT_ROOT/arch/x86/interrupts.asm"
    "$PROJECT_ROOT/arch/x86/pic.c"
    "$PROJECT_ROOT/arch/x86/pic.h"
    "$PROJECT_ROOT/arch/x86/timer.c"
    "$PROJECT_ROOT/arch/x86/timer.h"
    "$PROJECT_ROOT/arch/x86/paging.c"
    "$PROJECT_ROOT/arch/x86/paging.h"
    "$PROJECT_ROOT/kernel/main.c"
    "$PROJECT_ROOT/kernel/multiboot2.h"
    "$PROJECT_ROOT/kernel/string.c"
    "$PROJECT_ROOT/kernel/string.h"
    "$PROJECT_ROOT/kernel/pmm.c"
    "$PROJECT_ROOT/kernel/pmm.h"
    "$PROJECT_ROOT/kernel/vmm.c"
    "$PROJECT_ROOT/kernel/vmm.h"
    "$PROJECT_ROOT/kernel/heap.c"
    "$PROJECT_ROOT/kernel/heap.h"
    "$PROJECT_ROOT/kernel/arena.c"
    "$PROJECT_ROOT/kernel/arena.h"
    "$PROJECT_ROOT/kernel/hash.c"
    "$PROJECT_ROOT/kernel/hash.h"
    "$PROJECT_ROOT/kernel/ledger.c"
    "$PROJECT_ROOT/kernel/ledger.h"
    "$PROJECT_ROOT/kernel/ledger_queue.c"
    "$PROJECT_ROOT/kernel/ledger_queue.h"
    "$PROJECT_ROOT/kernel/process.c"
    "$PROJECT_ROOT/kernel/process.h"
    "$PROJECT_ROOT/kernel/scheduler.c"
    "$PROJECT_ROOT/kernel/scheduler.h"
    "$PROJECT_ROOT/kernel/syscall.c"
    "$PROJECT_ROOT/kernel/syscall.h"
    "$PROJECT_ROOT/kernel/vfs.c"
    "$PROJECT_ROOT/kernel/vfs.h"
    "$PROJECT_ROOT/user/shell/shell.c"
    "$PROJECT_ROOT/user/shell/shell.h"
    "$PROJECT_ROOT/user/lexer/token.h"
    "$PROJECT_ROOT/user/lexer/lexer.c"
    "$PROJECT_ROOT/user/lexer/lexer.h"
    "$PROJECT_ROOT/user/lexer/parser.c"
    "$PROJECT_ROOT/user/lexer/parser.h"
    "$PROJECT_ROOT/ipc/shared_surface.c"
    "$PROJECT_ROOT/ipc/shared_surface.h"
    "$PROJECT_ROOT/compositor/compositor.c"
    "$PROJECT_ROOT/compositor/window.c"
    "$PROJECT_ROOT/compositor/wm_events.c"
    "$PROJECT_ROOT/drivers/gfx/framebuffer.c"
    "$PROJECT_ROOT/drivers/gfx/font.c"
    "$PROJECT_ROOT/drivers/gfx/lvgl_bridge.c"
    "$PROJECT_ROOT/drivers/gfx/lvgl_input.c"
    "$PROJECT_ROOT/drivers/input/keyboard.c"
    "$PROJECT_ROOT/drivers/input/mouse.c"
    "$PROJECT_ROOT/drivers/serial/uart.c"
    "$PROJECT_ROOT/tools/nettools/luna_netstat.cpp"
    "$PROJECT_ROOT/tools/pentest/luna_portscan.cpp"
    "$PROJECT_ROOT/tools/forensics/luna_imager.cpp"
    "$PROJECT_ROOT/tools/crypto/luna_aes.asm"
    "$PROJECT_ROOT/tools/filehasher/luna_hash.asm"
    "$PROJECT_ROOT/apps/textedit/main.cpp"
    "$PROJECT_ROOT/apps/calculator/main.asm"
)

MISSING_FILES=0
FOUND_FILES=0

for file in "${FILES[@]}"; do
    if [ ! -f "$file" ]; then
        echo -e "  \033[0;31m[!] MISSING:\033[0m $file"
        MISSING_FILES=$((MISSING_FILES + 1))
    else
        echo -e "  \033[0;32m[✓] FOUND:\033[0m   $file"
        FOUND_FILES=$((FOUND_FILES + 1))
    fi
done

echo ""
echo "========================================================"
echo " SYSTEM VERIFICATION REPORT"
echo "========================================================"
echo " Files Found:   $FOUND_FILES"
echo " Files Missing: $MISSING_FILES"
echo "========================================================"